FROM ubuntu18.04
RUN apt update 
RUN apt upgrade -y
RUN apt install -y make openssl1.0  libcurl-openssl1.0-dev sasl2-bin libgsasl7-dev lua-cyrussasl-dev lib4store-dev software-properties-common gcc
#db4otool libdb4o-cil-dev software-properties-common
#RUN add-apt-repository -y ppa:bitcoin/bitcoin
#RUN apt-get update
RUN apt-get install libdb4.8-dev libdb4.8++-dev
COPY # ftp://ftp.porcupine.org/mirrors/postfix-release/official/postfix-3.5.6.tar.gz To MOUnted dir
RUN # tar xvf /XXX/postfix-3.5.6.tar.gz
RUN deluser www-data 
RUN groupadd -g 32 postfix &&
RUN groupadd -g 33 postdrop &&
RUN useradd -c "Postfix Daemon User" -d /var/spool/postfix -g postfix -s /bin/false -u 32 postfix &&
RUN chown -v postfix:postfix /var/mail
RUN # Put it all in easy dir for backups - make links on host from original location 
RUN sed -i 's/.\x08//g' README_FILES/*
RUN # cd INSTALLDIR/postfix-3.5.6 
RUN  make CCARGS="-DUSE_TLS -I/usr/include/openssl/ -DUSE_SASL_AUTH -DUSE_CYRUS_SASL -I/usr/include/sasl"  AUXLIBS="-lssl -lcrypto -lsasl2"  makefiles && make

#This follows - http://www.linuxfromscratch.org/blfs/view/svn/server/postfix.html

add-apt-repository ppa:bitcoin/bitcoin
apt-get update
apt-get install libdb4.8-dev libdb4.8++-dev

# RUN  make CCARGS="-DUSE_TLS -I/usr/include/openssl/"   AUXLIBS="-lssl -lcrypto"  makefiles && make
