FROM alpine:3.17

RUN addgroup -S postfix -g 105 2>/dev/null
RUN addgroup -S postdrop -g 106 2>/dev/null
RUN adduser -S -u 105 -H -h /var/spool/postfix -G postfix -g postfix postfix 2>/dev/null

### mail:x:12:mail,postfix - check whether mail group as gid 12 is in postfixadmin
RUN addgroup postfix mail 2>/dev/null

###vmail:x:101:102:vmail:/var/mail/domains:/sbin/nologin
RUN adduser -S -u 106 -H -h /var/mail/domains -s /sbin/nologin -G postdrop -g vmail vmail 2>/dev/null

# Install dependencies
RUN apk add --no-cache --update dovecot=2.3.20-r6 dovecot-pgsql=2.3.20-r6 bash dovecot-pop3d=2.3.20-r6 && \
    apk add --no-cache --upgrade musl=1.2.3-r4 musl-utils=1.2.3-r4 && \
    # Clean up
    (rm "/tmp/"* 2>/dev/null || true) && (rm -rf /var/cache/apk/* 2>/dev/null || true)

# Expose mail submission agent port
EXPOSE 25
EXPOSE 110
EXPOSE 143
EXPOSE 993
EXPOSE 995 

# Start postfix in foreground mode
CMD ["dovecot", "-F"]

# docker build -t dovecot -f Dockerfile-dovecot-alpine .
# docker run -id -p 25:25 -p 143:143 -p 993:993 -p 995:995 dovecot
