##Write script that creates dirs and users
# https://hub.docker.com/_/postgres
### VERy important put Db in volume
version: '3.7'
services:
   pgsql:
     container_name: pgsql
     image:  postgres:13.0-alpine 
     restart: unless-stopped
     environment:
       POSTGRES_PASSWORD: notSecureChangeMe
       POSTGRES_DB: postfixadmin
       POSTGRES_USER: postfixadmin
       # postgres_password sets it for the user not root - MYSQL_PASSWORD: postfixadminPassword  #### PUT into encrypted secrets
     ports:
       - "5432:5432"

   postfixadmin:
     # https://hub.docker.com/_/postfixadmin
     container_name: postfixadmin
     depends_on:
       - pgsql 
     image: postfixadmin:latest
     ports:
       - "80:80"
     restart: unless-stopped
     environment:
       POSTFIXADMIN_SETUP_PASSWORD: notSecureChangeMe
       POSTFIXADMIN_DB_TYPE: pgsql
       POSTFIXADMIN_DB_HOST: pgsql 
       POSTFIXADMIN_DB_USER: postfixadmin
       POSTFIXADMIN_DB_NAME: postfixadmin
       POSTFIXADMIN_DB_PASSWORD: notSecureChangeMe
       POSTFIXADMIN_SMTP_SERVER: postfix
       POSTFIXADMIN_SMTP_PORT: 25

   postfix:
     container_name: postfix_server
     build:  
       context: .
       dockerfile: Dockerfile-postfix-alpine
     restart: unless-stopped
     #environment: 
         # VARS HERE
     volumes:
       - ../docker-volumes/var/mail/domains/:/var/mail/domains/
       - ../docker-volumes/var/log:/var/log/
       - /dev/log:/dev/log
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro 
       - ../docker-volumes/etc/postfix/master.cf:/etc/postfix/master.cf
       - ../docker-volumes/etc/postfix/main.cf:/etc/postfix/main.cf
       - ../docker-volumes/etc/postfix/sql/:/etc/postfix/sql/
       - ../docker-volumes/var/spool/postfix/:/var/spool/postfix/
       - ../docker-volumes/var/spool/mail/:/var/spool/mail/

     ports:
       - "25:25"
       - "465:465"
       - "587:587"
   dovecot: 
     container_name: dovecot
     build:
       context: .
       dockerfile: Dockerfile-dovecot-alpine
     restart: unless-stopped
     volumes:
       ### ADD certbot /etc certs HERE
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
     ports:
       - 143:143
       - 993:993
       - 995:995 
