#FROM certbot/certbot:v1.19.0
FROM certbot/certbot:arm64v8-v2.0.0
RUN apk update && apk add curl
RUN mkdir -p /var/log/letsencrypt/
RUN /bin/ln -sf /dev/stderr /var/log/letsencrypt/letsencrypt.log 